"""
services/decision_dossier.py
─────────────────────────────
Decision Dossier scaffold for Phase 1 VLM optimization.

The Decision Dossier is a structured human-readable document that the
Search Strategist generates when the Threshold Monitor fires (i.e., when
the Pareto frontier hasn't improved in N consecutive experiments).

It summarises:
  - Current Pareto frontier
  - What was tried (experiment history with outcomes)
  - Why the agent is stuck (pattern analysis)
  - Candidate next actions for the human to consider

Phase 1 usage: the scaffold exists and the Threshold Monitor is defined,
but the dossier is not expected to fire in Phase 1 (only 3+ consecutive
non-improvements triggers it, which hasn't happened yet). Phase 2 can
call generate_dossier() when the monitor fires autonomously.

Usage:
    from services.decision_dossier import ThresholdMonitor, generate_dossier

    monitor = ThresholdMonitor(threshold=3)
    if monitor.should_fire():
        path = generate_dossier()
        print(f"Dossier written to {path}")
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

# ── Project root ──────────────────────────────────────────────────────────────

_HERE        = Path(__file__).parent
PROJECT_ROOT = _HERE.parent
DOSSIER_DIR  = PROJECT_ROOT / "artifacts" / "dossiers"
LEDGER_DIR   = PROJECT_ROOT / "artifacts" / "experiment_ledger"


# ── Threshold Monitor ─────────────────────────────────────────────────────────

class ThresholdMonitor:
    """
    Monitors the Pareto frontier for stagnation.

    Fires when the last `threshold` completed experiments all failed to
    advance the Pareto frontier (i.e., all are dominated points).

    Args:
        threshold: number of consecutive non-improvements before firing.
                   Default: 3 (matches Search Strategist policy).
    """

    def __init__(self, threshold: int = 3):
        self.threshold = threshold
        self._consecutive: int | None = None

    def check(self) -> tuple[bool, int]:
        """
        Returns (should_fire: bool, consecutive_count: int).
        Reads the frontier fresh each call.
        """
        from services.pareto_tracker import ParetoTracker
        tracker = ParetoTracker()
        tracker.update()

        dominated_ids = {
            p.experiment_id for p in tracker.points
            if not p.is_pareto_frontier and not p.is_baseline
        }
        frontier_ids = {
            p.experiment_id for p in tracker.points
            if p.is_pareto_frontier and not p.is_baseline
        }

        # Walk ledger most-recent-first
        ledger_files = sorted(
            (p for p in LEDGER_DIR.glob("*.json") if not p.stem.endswith("_preds")),
            key=lambda p: p.stat().st_mtime,
        )

        consecutive = 0
        for path in reversed(ledger_files):
            try:
                data  = json.loads(path.read_text())
                exp_id = data["report"]["experiment_id"]
                status = data["report"].get("status")
            except Exception:
                continue

            if status not in ("completed",):
                continue
            # Skip Mac-only proxy runs (no iPhone perf) — don't count toward streak
            if data["report"].get("ttft_ms") is None and data["report"].get("decode_tokens_per_sec") is None:
                continue

            if exp_id in frontier_ids:
                break   # hit a frontier point → reset count
            if exp_id in dominated_ids:
                consecutive += 1

        self._consecutive = consecutive
        should_fire = consecutive >= self.threshold
        return should_fire, consecutive

    def should_fire(self) -> bool:
        fired, _ = self.check()
        return fired

    @property
    def consecutive_count(self) -> int:
        if self._consecutive is None:
            _, count = self.check()
        return self._consecutive  # type: ignore[return-value]


# ── Dossier generator ─────────────────────────────────────────────────────────

DOSSIER_TEMPLATE = """\
# Decision Dossier — Phase 1 VLM Optimization
**Generated:** {generated_at}
**Trigger:** Threshold Monitor fired after {consecutive} consecutive non-improvements

---

## 1. Current Pareto Frontier

{frontier_table}

---

## 2. Experiment History

{history_table}

---

## 3. Why We're Stuck

{stuck_analysis}

---

## 4. Candidate Next Actions

{candidate_actions}

---

## 5. Recommended Action

{recommendation}

---
*This dossier was auto-generated by `services/decision_dossier.py` when the
Threshold Monitor fired. A human should review and decide before the next
experiment is dispatched.*
"""


def generate_dossier(
    consecutive: int | None = None,
    stuck_analysis: str = "(auto-generated — fill in with agent reasoning)",
    candidate_actions: list[str] | None = None,
    recommendation: str = "(pending human review)",
    output_dir: Path | None = None,
    request_escalation: bool = False,
) -> Path:
    """
    Generate a Decision Dossier markdown file and save it to disk.

    Args:
        consecutive:       number of consecutive non-improvements that triggered this.
        stuck_analysis:    free-text explanation of why the frontier isn't improving.
        candidate_actions: list of candidate next-step strings.
        recommendation:    recommended action for the human.
        output_dir:        where to write the dossier (default: artifacts/dossiers/).

    Returns the path of the written dossier file.
    """
    from services.pareto_tracker import ParetoTracker

    if consecutive is None:
        monitor    = ThresholdMonitor()
        _, consecutive = monitor.check()

    if candidate_actions is None:
        candidate_actions = [
            "Try H006 (GPTQ INT4) — calibrated quantization may yield quality improvement",
            "Try H007 (FastVLM 0.5B) — different architecture may have better native TTFT",
            "Add H008: experiment with n_threads (parallelism on A18 Pro)",
            "Broaden search to Phase 2 techniques (distillation from larger model)",
        ]

    # Build frontier table
    tracker = ParetoTracker()
    tracker.update()
    frontier_rows = []
    for p in sorted(
        (x for x in tracker.points if x.is_pareto_frontier),
        key=lambda x: (x.clip_score or 0),
        reverse=True,
    ):
        tag = " *(baseline)*" if p.is_baseline else " ⭐"
        cs  = f"{p.clip_score:.2f}" if p.clip_score  else "—"
        ts  = f"{p.ttft_ms:.1f}" if p.ttft_ms         else "—"
        ps  = f"{p.decode_tokens_per_sec:.1f}" if p.decode_tokens_per_sec else "—"
        ms  = f"{p.peak_memory_mb:.0f}" if p.peak_memory_mb else "—"
        frontier_rows.append(f"| {p.label}{tag} | {cs} | {ts} | {ps} | {ms} |")

    frontier_table = (
        "| Model | CLIP | TTFT ms | TPS | Mem MB |\n"
        "|---|---|---|---|---|\n"
        + "\n".join(frontier_rows)
    )

    # Build history table
    history_rows = []
    for path in sorted(LEDGER_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime):
        if path.stem.endswith("_preds"):
            continue
        try:
            data   = json.loads(path.read_text())
            rep    = data["report"]
            cfg    = data.get("config", {})
            exp_id = rep["experiment_id"][:12] + "…"
            status = rep.get("status", "?")
            qs     = {s["metric"]: s["value"] for s in rep.get("quality_scores", [])}
            clip   = f"{qs.get('clip_score_mean', 0):.2f}" if qs.get("clip_score_mean") else "—"
            ttft   = f"{rep['ttft_ms']:.1f}" if rep.get("ttft_ms") else "—"
            pareto = "✅" if any(
                p.experiment_id == rep["experiment_id"] and p.is_pareto_frontier
                for p in tracker.points
            ) else "❌"
            technique = cfg.get("notes", cfg.get("compression", {}).get("weight_dtype", "?"))[:40]
            history_rows.append(f"| `{exp_id}` | {technique} | {clip} | {ttft} | {pareto} |")
        except Exception:
            continue

    history_table = (
        "| Experiment | Technique | CLIP | TTFT ms | Frontier? |\n"
        "|---|---|---|---|---|\n"
        + "\n".join(history_rows)
    )

    # Format candidate actions
    actions_md = "\n".join(f"{i+1}. {a}" for i, a in enumerate(candidate_actions))

    # Write dossier
    out_dir = Path(output_dir) if output_dir else DOSSIER_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    ts       = datetime.now(timezone.utc)
    filename = f"dossier_{ts.strftime('%Y%m%d_%H%M%S')}.md"
    path     = out_dir / filename

    content = DOSSIER_TEMPLATE.format(
        generated_at=ts.isoformat(),
        consecutive=consecutive,
        frontier_table=frontier_table,
        history_table=history_table,
        stuck_analysis=stuck_analysis,
        candidate_actions=actions_md,
        recommendation=recommendation,
    )
    path.write_text(content)

    # HLD §4.2: the dossier posts the Mode-A→Mode-B escalation to the approval queue.
    if request_escalation:
        from services import gates
        gates.gate_mode_b_escalation(dossier_path=path, block=False,
                                     consecutive=consecutive)

    return path


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    monitor  = ThresholdMonitor(threshold=3)
    fired, n = monitor.check()

    print(f"\nThreshold Monitor:")
    print(f"  Consecutive non-improvements: {n}")
    print(f"  Threshold:                    {monitor.threshold}")
    print(f"  Should fire:                  {fired}")

    if fired:
        path = generate_dossier(consecutive=n)
        print(f"\n  ⚠️  Dossier generated: {path}")
    else:
        print(f"\n  ✅ Below threshold — no dossier needed.")
        print(f"     ({monitor.threshold - n} more non-improvements before threshold)")
